package keysym

const (
 XKBackSpace                =     0xff08  /* Back space, back char */
 XKTab                      =     0xff09
 XKLinefeed                 =     0xff0a  /* Linefeed, LF */
 XKClear                    =     0xff0b
 XKReturn                   =     0xff0d  /* Return, enter */
 XKPause                    =     0xff13  /* Pause, hold */
 XKScrollLock              =     0xff14
 XKSysReq                  =     0xff15
 XKEscape                   =     0xff1b
 XKDelete                   =     0xffff  /* Delete, rubout */



/* International & multi-key =character composition */

 XKMultikey                =     0xff20  /* Multi-key character compose */
 XKCodeinput                =     0xff37
 XKSingleCandidate          =     0xff3c
 XKMultipleCandidate        =     0xff3d
 XKPreviousCandidate        =     0xff3e
/* Japanese keyboard support */
 XKKanji                    =     0xff21  /* Kanji, Kanji convert */
 XKMuhenkan                 =     0xff22  /* Cancel Conversion */
 XKHenkanMode              =     0xff23  /* Start/Stop Conversion */
 XKHenkan                   =     0xff23  /* Alias for HenkanMode */
 XKRomaji                   =     0xff24  /* to Romaji */
 XKHiragana                 =     0xff25  /* to Hiragana */
 XKKatakana                 =     0xff26  /* to Katakana */
 XKHiraganaKatakana        =     0xff27  /* Hiragana/Katakana toggle */
 XKZenkaku                  =     0xff28  /* to Zenkaku */
 XKHankaku                  =     0xff29  /* to Hankaku */
 XKZenkakuHankaku          =     0xff2a  /* Zenkaku/Hankaku toggle */
 XKTouroku                  =     0xff2b  /* Add to Dictionary */
 XKMassyo                   =     0xff2c  /* Delete from Dictionary */
 XKKanaLock                =     0xff2d  /* Kana Lock */
 XKKanaShift               =     0xff2e  /* Kana Shift */
 XKEisuShift               =     0xff2f  /* Alphanumeric Shift */
 XKEisutoggle              =     0xff30  /* Alphanumeric toggle */
 XKKanjiBangou             =     0xff37  /* Codeinput */
 XKZenKoho                 =     0xff3d  /* Multiple/All Candidate(s) */
 XKMaeKoho                 =     0xff3e  /* Previous Candidate */
/* 0xff31 thru 0xff3f are und=er XKKOREAN */
/* Cursor control & motion */
 XKHome                     =     0xff50
 XKLeft                     =     0xff51  /* Move left, left arrow */
 XKUp                       =     0xff52  /* Move up, up arrow */
 XKRight                    =     0xff53  /* Move right, right arrow */
 XKDown                     =     0xff54  /* Move down, down arrow */
 XKPrior                    =     0xff55  /* Prior, previous */
 XKPageUp                  =     0xff55
 XKNext                     =     0xff56  /* Next */
 XKPageDown                =     0xff56
 XKEnd                      =     0xff57  /* EOL */
 XKBegin                    =     0xff58  /* BOL */


/* Misc functions */
 XKSelect                   =     0xff60  /* Select, mark */
 XKPrint                    =     0xff61
 XKExecute                  =     0xff62  /* Execute, run, do */
 XKInsert                   =     0xff63  /* Insert, insert here */
 XKUndo                     =     0xff65
 XKRedo                     =     0xff66  /* Redo, again */
 XKMenu                     =     0xff67
 XKFind                     =     0xff68  /* Find, search */
 XKCancel                   =     0xff69  /* Cancel, stop, abort, exit */
 XKHelp                     =     0xff6a  /* Help */
 XKBreak                    =     0xff6b
 XKModeswitch              =     0xff7e  /* Character set switch */
 XKscriptswitch            =     0xff7e  /* Alias for modeswitch */
 XKNumLock                 =     0xff7f

/* Keypad functions, keypad n=umbers cleverly chosen to map to ASCII */

 XKKPSpace                 =     0xff80  /* Space */
 XKKPTab                   =     0xff89
 XKKPEnter                 =     0xff8d  /* Enter */
 XKKPF1                    =     0xff91  /* PF1, KPA, ... */
 XKKPF2                    =     0xff92
 XKKPF3                    =     0xff93
 XKKPF4                    =     0xff94
 XKKPHome                  =     0xff95
 XKKPLeft                  =     0xff96
 XKKPUp                    =     0xff97
 XKKPRight                 =     0xff98
 XKKPDown                  =     0xff99
 XKKPPrior                 =     0xff9a
 XKKPPageUp               =     0xff9a
 XKKPNext                  =     0xff9b
 XKKPPageDown             =     0xff9b
 XKKPEnd                   =     0xff9c
 XKKPBegin                 =     0xff9d
 XKKPInsert                =     0xff9e
 XKKPDelete                =     0xff9f
 XKKPEqual                 =     0xffbd  /* Equals */
 XKKPMultiply              =     0xffaa
 XKKPAdd                   =     0xffab
 XKKPSeparator             =     0xffac  /* Separator, often comma */
 XKKPSubtract              =     0xffad
 XKKPDecimal               =     0xffae
 XKKPDivide                =     0xffaf

 XKKP0                     =     0xffb0
 XKKP1                     =     0xffb1
 XKKP2                     =     0xffb2
 XKKP3                     =     0xffb3
 XKKP4                     =     0xffb4
 XKKP5                     =     0xffb5
 XKKP6                     =     0xffb6
 XKKP7                     =     0xffb7
 XKKP8                     =     0xffb8
 XKKP9                     =     0xffb9


 XKF1                       =     0xffbe
 XKF2                       =     0xffbf
 XKF3                       =     0xffc0
 XKF4                       =     0xffc1
 XKF5                       =     0xffc2
 XKF6                       =     0xffc3
 XKF7                       =     0xffc4
 XKF8                       =     0xffc5
 XKF9                       =     0xffc6
 XKF10                      =     0xffc7
 XKF11                      =     0xffc8
 XKL1                       =     0xffc8
 XKF12                      =     0xffc9
 XKL2                       =     0xffc9
 XKF13                      =     0xffca
 XKL3                       =     0xffca
 XKF14                      =     0xffcb
 XKL4                       =     0xffcb
 XKF15                      =     0xffcc
 XKL5                       =     0xffcc
 XKF16                      =     0xffcd
 XKL6                       =     0xffcd
 XKF17                      =     0xffce
 XKL7                       =     0xffce
 XKF18                      =     0xffcf
 XKL8                       =     0xffcf
 XKF19                      =     0xffd0
 XKL9                       =     0xffd0
 XKF20                      =     0xffd1
 XKL10                      =     0xffd1
 XKF21                      =     0xffd2
 XKR1                       =     0xffd2
 XKF22                      =     0xffd3
 XKR2                       =     0xffd3
 XKF23                      =     0xffd4
 XKR3                       =     0xffd4
 XKF24                      =     0xffd5
 XKR4                       =     0xffd5
 XKF25                      =     0xffd6
 XKR5                       =     0xffd6
 XKF26                      =     0xffd7
 XKR6                       =     0xffd7
 XKF27                      =     0xffd8
 XKR7                       =     0xffd8
 XKF28                      =     0xffd9
 XKR8                       =     0xffd9
 XKF29                      =     0xffda
 XKR9                       =     0xffda
 XKF30                      =     0xffdb
 XKR10                      =     0xffdb
 XKF31                      =     0xffdc
 XKR11                      =     0xffdc
 XKF32                      =     0xffdd
 XKR12                      =     0xffdd
 XKF33                      =     0xffde
 XKR13                      =     0xffde
 XKF34                      =     0xffdf
 XKR14                      =     0xffdf
 XKF35                      =     0xffe0
 XKR15                      =     0xffe0

/* Modifiers */
 XKShiftL                  =     0xffe1  /* Left shift */
 XKShiftR                  =     0xffe2  /* Right shift */
 XKControlL                =     0xffe3  /* Left control */
 XKControlR                =     0xffe4  /* Right control */
 XKCapsLock                =     0xffe5  /* Caps lock */
 XKShiftLock               =     0xffe6  /* Shift lock */

 XKMetaL                   =     0xffe7  /* Left meta */
 XKMetaR                   =     0xffe8  /* Right meta */
 XKAltL                    =     0xffe9  /* Left alt */
 XKAltR                    =     0xffea  /* Right alt */
 XKSuperL                  =     0xffeb  /* Left super */
 XKSuperR                  =     0xffec  /* Right super */
 XKHyperL                  =     0xffed  /* Left hyper */
 XKHyperR                  =     0xffee  /* Right hyper */

/* * Keyboard (XKB) Extension function and modifier keys
 * (from Appendix C of "The X Keyboard Extension: Protocol Specification")
 * Byte 3 = 0xfe */

 XKISOLock                 =     0xfe01
 XKISOLevel2Latch         =     0xfe02
 XKISOLevel3Shift         =     0xfe03
 XKISOLevel3Latch         =     0xfe04
 XKISOLevel3Lock          =     0xfe05
 XKISOGroupShift          =     0xff7e  /* Alias for modeswitch */
 XKISOGroupLatch          =     0xfe06
 XKISOGroupLock           =     0xfe07
 XKISONextGroup           =     0xfe08
 XKISONextGroupLock      =     0xfe09
 XKISOPrevGroup           =     0xfe0a
 XKISOPrevGroupLock      =     0xfe0b
 XKISOFirstGroup          =     0xfe0c
 XKISOFirstGroupLock     =     0xfe0d
 XKISOLastGroup           =     0xfe0e
 XKISOLastGroupLock      =     0xfe0f

 XKISOLeftTab             =     0xfe20
 XKISOMoveLineUp         =     0xfe21
 XKISOMoveLineDown       =     0xfe22
 XKISOPartialLineUp      =     0xfe23
 XKISOPartialLineDown    =     0xfe24
 XKISOPartialSpaceLeft   =     0xfe25
 XKISOPartialSpaceRight  =     0xfe26
 XKISOSetMarginLeft      =     0xfe27
 XKISOSetMarginRight     =     0xfe28
 XKISOReleaseMarginLeft  =     0xfe29
 XKISOReleaseMarginRight =     0xfe2a
 XKISOReleaseBothMargins =     0xfe2b
 XKISOFastCursorLeft     =     0xfe2c
 XKISOFastCursorRight    =     0xfe2d
 XKISOFastCursorUp       =     0xfe2e
 XKISOFastCursorDown     =     0xfe2f
 XKISOContinuousUnderline =     0xfe30
 XKISODiscontinuousUnderline =  0xfe31
 XKISOEmphasize            =     0xfe32
 XKISOCenterObject        =     0xfe33
 XKISOEnter                =     0xfe34

 XKdeadgrave               =     0xfe50
 XKdeadacute               =     0xfe51
 XKdeadcircumflex          =     0xfe52
 XKdeadtilde               =     0xfe53
 XKdeadmacron              =     0xfe54
 XKdeadbreve               =     0xfe55
 XKdeadabovedot            =     0xfe56
 XKdeaddiaeresis           =     0xfe57
 XKdeadabovering           =     0xfe58
 XKdeaddoubleacute         =     0xfe59
 XKdeadcaron               =     0xfe5a
 XKdeadcedilla             =     0xfe5b
 XKdeadogonek              =     0xfe5c
 XKdeadiota                =     0xfe5d
 XKdeadvoicedsound        =     0xfe5e
 XKdeadsemivoicedsound    =     0xfe5f
 XKdeadbelowdot            =     0xfe60
 XKdeadhook                =     0xfe61
 XKdeadhorn                =     0xfe62

 XKFirstVirtualScreen     =     0xfed0
 XKPrevVirtualScreen      =     0xfed1
 XKNextVirtualScreen      =     0xfed2
 XKLastVirtualScreen      =     0xfed4
 XKTerminateServer         =     0xfed5

 XKAccessXEnable           =     0xfe70
 XKAccessXFeedbackEnable  =     0xfe71
 XKRepeatKeysEnable        =     0xfe72
 XKSlowKeysEnable          =     0xfe73
 XKBounceKeysEnable        =     0xfe74
 XKStickyKeysEnable        =     0xfe75
 XKMouseKeysEnable         =     0xfe76
 XKMouseKeysAccelEnable   =     0xfe77
 XKOverlay1Enable          =     0xfe78
 XKOverlay2Enable          =     0xfe79
 XKAudibleBellEnable       =     0xfe7a

 XKPointerLeft             =     0xfee0
 XKPointerRight            =     0xfee1
 XKPointerUp               =     0xfee2
 XKPointerDown             =     0xfee3
 XKPointerUpLeft           =     0xfee4
 XKPointerUpRight          =     0xfee5
 XKPointerDownLeft         =     0xfee6
 XKPointerDownRight        =     0xfee7
 XKPointerButtonDflt      =     0xfee8
 XKPointerButton1          =     0xfee9
 XKPointerButton2          =     0xfeea
 XKPointerButton3          =     0xfeeb
 XKPointerButton4          =     0xfeec
 XKPointerButton5          =     0xfeed
 XKPointerDblClickDflt    =     0xfeee
 XKPointerDblClick1        =     0xfeef
 XKPointerDblClick2        =     0xfef0
 XKPointerDblClick3        =     0xfef1
 XKPointerDblClick4        =     0xfef2
 XKPointerDblClick5        =     0xfef3
 XKPointerDragDflt        =     0xfef4
 XKPointerDrag1            =     0xfef5
 XKPointerDrag2            =     0xfef6
 XKPointerDrag3            =     0xfef7
 XKPointerDrag4            =     0xfef8
 XKPointerDrag5            =     0xfefd

 XKPointerEnableKeys       =     0xfef9
 XKPointerAccelerate       =     0xfefa
 XKPointerDfltBtnNext      =     0xfefb
 XKPointerDfltBtnPrev      =     0xfefc


/* * 3270 Terminal Keys * Byte 3 = 0xfd */
 XK3270Duplicate           =     0xfd01
 XK3270FieldMark           =     0xfd02
 XK3270Right2              =     0xfd03
 XK3270Left2               =     0xfd04
 XK3270BackTab             =     0xfd05
 XK3270EraseEOF            =     0xfd06
 XK3270EraseInput          =     0xfd07
 XK3270Reset               =     0xfd08
 XK3270Quit                =     0xfd09
 XK3270PA1                 =     0xfd0a
 XK3270PA2                 =     0xfd0b
 XK3270PA3                 =     0xfd0c
 XK3270Test                =     0xfd0d
 XK3270Attn                =     0xfd0e
 XK3270CursorBlink         =     0xfd0f
 XK3270AltCursor           =     0xfd10
 XK3270KeyClick            =     0xfd11
 XK3270Jump                =     0xfd12
 XK3270Ident               =     0xfd13
 XK3270Rule                =     0xfd14
 XK3270Copy                =     0xfd15
 XK3270Play                =     0xfd16
 XK3270Setup               =     0xfd17
 XK3270Record              =     0xfd18
 XK3270ChangeScreen        =     0xfd19
 XK3270DeleteWord          =     0xfd1a
 XK3270ExSelect            =     0xfd1b
 XK3270CursorSelect        =     0xfd1c
 XK3270PrintScreen         =     0xfd1d
 XK3270Enter               =     0xfd1e

/* * Latin 1 * (ISO/IEC 8859-1 = Unicode =U+0020..U+00FF)
 * Byte 3 = 0 */
 XKspace                    =     0x0020  /* U+0020 SPACE */
 XKexclam                   =     0x0021  /* U+0021 EXCLAMATION MARK */
 XKquotedbl                 =     0x0022  /* U+0022 QUOTATION MARK */
 XKnumbersign               =     0x0023  /* U+0023 NUMBER SIGN */
 XKdollar                   =     0x0024  /* U+0024 DOLLAR SIGN */
 XKpercent                  =     0x0025  /* U+0025 PERCENT SIGN */
 XKampersand                =     0x0026  /* U+0026 AMPERSAND */
 XKapostrophe               =     0x0027  /* U+0027 APOSTROPHE */
 XKquoteright               =     0x0027  /* deprecated */
 XKparenleft                =     0x0028  /* U+0028 LEFT PARENTHESIS */
 XKparenright               =     0x0029  /* U+0029 RIGHT PARENTHESIS */
 XKasterisk                 =     0x002a  /* U+002A ASTERISK */
 XKplus                     =     0x002b  /* U+002B PLUS SIGN */
 XKcomma                    =     0x002c  /* U+002C COMMA */
 XKminus                    =     0x002d  /* U+002D HYPHEN-MINUS */
 XKperiod                   =     0x002e  /* U+002E FULL STOP */
 XKslash                    =     0x002f  /* U+002F SOLIDUS */
 XK0                        =     0x0030  /* U+0030 DIGIT ZERO */
 XK1                        =     0x0031  /* U+0031 DIGIT ONE */
 XK2                        =     0x0032  /* U+0032 DIGIT TWO */
 XK3                        =     0x0033  /* U+0033 DIGIT THREE */
 XK4                        =     0x0034  /* U+0034 DIGIT FOUR */
 XK5                        =     0x0035  /* U+0035 DIGIT FIVE */
 XK6                        =     0x0036  /* U+0036 DIGIT SIX */
 XK7                        =     0x0037  /* U+0037 DIGIT SEVEN */
 XK8                        =     0x0038  /* U+0038 DIGIT EIGHT */
 XK9                        =     0x0039  /* U+0039 DIGIT NINE */
 XKcolon                    =     0x003a  /* U+003A COLON */
 XKsemicolon                =     0x003b  /* U+003B SEMICOLON */
 XKless                     =     0x003c  /* U+003C LESS-THAN SIGN */
 XKequal                    =     0x003d  /* U+003D EQUALS SIGN */
 XKgreater                  =     0x003e  /* U+003E GREATER-THAN SIGN */
 XKquestion                 =     0x003f  /* U+003F QUESTION MARK */
 XKat                       =     0x0040  /* U+0040 COMMERCIAL AT */
 XKA                        =     0x0041  /* U+0041 LATIN CAPITAL LETTER A */
 XKB                        =     0x0042  /* U+0042 LATIN CAPITAL LETTER B */
 XKC                        =     0x0043  /* U+0043 LATIN CAPITAL LETTER C */
 XKD                        =     0x0044  /* U+0044 LATIN CAPITAL LETTER D */
 XKE                        =     0x0045  /* U+0045 LATIN CAPITAL LETTER E */
 XKF                        =     0x0046  /* U+0046 LATIN CAPITAL LETTER F */
 XKG                        =     0x0047  /* U+0047 LATIN CAPITAL LETTER G */
 XKH                        =     0x0048  /* U+0048 LATIN CAPITAL LETTER H */
 XKI                        =     0x0049  /* U+0049 LATIN CAPITAL LETTER I */
 XKJ                        =     0x004a  /* U+004A LATIN CAPITAL LETTER J */
 XKK                        =     0x004b  /* U+004B LATIN CAPITAL LETTER K */
 XKL                        =     0x004c  /* U+004C LATIN CAPITAL LETTER L */
 XKM                        =     0x004d  /* U+004D LATIN CAPITAL LETTER M */
 XKN                        =     0x004e  /* U+004E LATIN CAPITAL LETTER N */
 XKO                        =     0x004f  /* U+004F LATIN CAPITAL LETTER O */
 XKP                        =     0x0050  /* U+0050 LATIN CAPITAL LETTER P */
 XKQ                        =     0x0051  /* U+0051 LATIN CAPITAL LETTER Q */
 XKR                        =     0x0052  /* U+0052 LATIN CAPITAL LETTER R */
 XKS                        =     0x0053  /* U+0053 LATIN CAPITAL LETTER S */
 XKT                        =     0x0054  /* U+0054 LATIN CAPITAL LETTER T */
 XKU                        =     0x0055  /* U+0055 LATIN CAPITAL LETTER U */
 XKV                        =     0x0056  /* U+0056 LATIN CAPITAL LETTER V */
 XKW                        =     0x0057  /* U+0057 LATIN CAPITAL LETTER W */
 XKX                        =     0x0058  /* U+0058 LATIN CAPITAL LETTER X */
 XKY                        =     0x0059  /* U+0059 LATIN CAPITAL LETTER Y */
 XKZ                        =     0x005a  /* U+005A LATIN CAPITAL LETTER Z */
 XKbracketleft              =     0x005b  /* U+005B LEFT SQUARE BRACKET */
 XKbackslash                =     0x005c  /* U+005C REVERSE SOLIDUS */
 XKbracketright             =     0x005d  /* U+005D RIGHT SQUARE BRACKET */
 XKasciicircum              =     0x005e  /* U+005E CIRCUMFLEX ACCENT */
 XKunderscore               =     0x005f  /* U+005F LOW LINE */
 XKgrave                    =     0x0060  /* U+0060 GRAVE ACCENT */
 XKquoteleft                =     0x0060  /* deprecated */
 XKa                        =     0x0061  /* U+0061 LATIN SMALL LETTER A */
 XKb                        =     0x0062  /* U+0062 LATIN SMALL LETTER B */
 XKc                        =     0x0063  /* U+0063 LATIN SMALL LETTER C */
 XKd                        =     0x0064  /* U+0064 LATIN SMALL LETTER D */
 XKe                        =     0x0065  /* U+0065 LATIN SMALL LETTER E */
 XKf                        =     0x0066  /* U+0066 LATIN SMALL LETTER F */
 XKg                        =     0x0067  /* U+0067 LATIN SMALL LETTER G */
 XKh                        =     0x0068  /* U+0068 LATIN SMALL LETTER H */
 XKi                        =     0x0069  /* U+0069 LATIN SMALL LETTER I */
 XKj                        =     0x006a  /* U+006A LATIN SMALL LETTER J */
 XKk                        =     0x006b  /* U+006B LATIN SMALL LETTER K */
 XKl                        =     0x006c  /* U+006C LATIN SMALL LETTER L */
 XKm                        =     0x006d  /* U+006D LATIN SMALL LETTER M */
 XKn                        =     0x006e  /* U+006E LATIN SMALL LETTER N */
 XKo                        =     0x006f  /* U+006F LATIN SMALL LETTER O */
 XKp                        =     0x0070  /* U+0070 LATIN SMALL LETTER P */
 XKq                        =     0x0071  /* U+0071 LATIN SMALL LETTER Q */
 XKr                        =     0x0072  /* U+0072 LATIN SMALL LETTER R */
 XKs                        =     0x0073  /* U+0073 LATIN SMALL LETTER S */
 XKt                        =     0x0074  /* U+0074 LATIN SMALL LETTER T */
 XKu                        =     0x0075  /* U+0075 LATIN SMALL LETTER U */
 XKv                        =     0x0076  /* U+0076 LATIN SMALL LETTER V */
 XKw                        =     0x0077  /* U+0077 LATIN SMALL LETTER W */
 XKx                        =     0x0078  /* U+0078 LATIN SMALL LETTER X */
 XKy                        =     0x0079  /* U+0079 LATIN SMALL LETTER Y */
 XKz                        =     0x007a  /* U+007A LATIN SMALL LETTER Z */
 XKbraceleft                =     0x007b  /* U+007B LEFT CURLY BRACKET */
 XKbar                      =     0x007c  /* U+007C VERTICAL LINE */
 XKbraceright               =     0x007d  /* U+007D RIGHT CURLY BRACKET */
 XKasciitilde               =     0x007e  /* U+007E TILDE */

 XKnobreakspace             =     0x00a0  /* U+00A0 NO-BREAK SPACE */
 XKexclamdown               =     0x00a1  /* U+00A1 INVERTED EXCLAMATION MARK */
 XKcent                     =     0x00a2  /* U+00A2 CENT SIGN */
 XKsterling                 =     0x00a3  /* U+00A3 POUND SIGN */
 XKcurrency                 =     0x00a4  /* U+00A4 CURRENCY SIGN */
 XKyen                      =     0x00a5  /* U+00A5 YEN SIGN */
 XKbrokenbar                =     0x00a6  /* U+00A6 BROKEN BAR */
 XKsection                  =     0x00a7  /* U+00A7 SECTION SIGN */
 XKdiaeresis                =     0x00a8  /* U+00A8 DIAERESIS */
 XKcopyright                =     0x00a9  /* U+00A9 COPYRIGHT SIGN */
 XKordfeminine              =     0x00aa  /* U+00AA FEMININE ORDINAL INDICATOR */
 XKguillemotleft            =     0x00ab  /* U+00AB LEFT-POINTING DOUBLE ANGLE QUOTATION MARK */
 XKnotsign                  =     0x00ac  /* U+00AC NOT SIGN */
 XKhyphen                   =     0x00ad  /* U+00AD SOFT HYPHEN */
 XKregistered               =     0x00ae  /* U+00AE REGISTERED SIGN */
 XKmacron                   =     0x00af  /* U+00AF MACRON */
 XKdegree                   =     0x00b0  /* U+00B0 DEGREE SIGN */
 XKplusminus                =     0x00b1  /* U+00B1 PLUS-MINUS SIGN */
 XKtwosuperior              =     0x00b2  /* U+00B2 SUPERSCRIPT TWO */
 XKthreesuperior            =     0x00b3  /* U+00B3 SUPERSCRIPT THREE */
 XKacute                    =     0x00b4  /* U+00B4 ACUTE ACCENT */
 XKmu                       =     0x00b5  /* U+00B5 MICRO SIGN */
 XKparagraph                =     0x00b6  /* U+00B6 PILCROW SIGN */
 XKperiodcentered           =     0x00b7  /* U+00B7 MIDDLE DOT */
 XKcedilla                  =     0x00b8  /* U+00B8 CEDILLA */
 XKonesuperior              =     0x00b9  /* U+00B9 SUPERSCRIPT ONE */
 XKmasculine                =     0x00ba  /* U+00BA MASCULINE ORDINAL INDICATOR */
 XKguillemotright           =     0x00bb  /* U+00BB RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK */
 XKonequarter               =     0x00bc  /* U+00BC VULGAR FRACTION ONE QUARTER */
 XKonehalf                  =     0x00bd  /* U+00BD VULGAR FRACTION ONE HALF */
 XKthreequarters            =     0x00be  /* U+00BE VULGAR FRACTION THREE QUARTERS */
 XKquestiondown             =     0x00bf  /* U+00BF INVERTED QUESTION MARK */
 XKAgrave                   =     0x00c0  /* U+00C0 LATIN CAPITAL LETTER A WITH GRAVE */
 XKAacute                   =     0x00c1  /* U+00C1 LATIN CAPITAL LETTER A WITH ACUTE */
 XKAcircumflex              =     0x00c2  /* U+00C2 LATIN CAPITAL LETTER A WITH CIRCUMFLEX */
 XKAtilde                   =     0x00c3  /* U+00C3 LATIN CAPITAL LETTER A WITH TILDE */
 XKAdiaeresis               =     0x00c4  /* U+00C4 LATIN CAPITAL LETTER A WITH DIAERESIS */
 XKAring                    =     0x00c5  /* U+00C5 LATIN CAPITAL LETTER A WITH RING ABOVE */
 XKAE                       =     0x00c6  /* U+00C6 LATIN CAPITAL LETTER AE */
 XKCcedilla                 =     0x00c7  /* U+00C7 LATIN CAPITAL LETTER C WITH CEDILLA */
 XKEgrave                   =     0x00c8  /* U+00C8 LATIN CAPITAL LETTER E WITH GRAVE */
 XKEacute                   =     0x00c9  /* U+00C9 LATIN CAPITAL LETTER E WITH ACUTE */
 XKEcircumflex              =     0x00ca  /* U+00CA LATIN CAPITAL LETTER E WITH CIRCUMFLEX */
 XKEdiaeresis               =     0x00cb  /* U+00CB LATIN CAPITAL LETTER E WITH DIAERESIS */
 XKIgrave                   =     0x00cc  /* U+00CC LATIN CAPITAL LETTER I WITH GRAVE */
 XKIacute                   =     0x00cd  /* U+00CD LATIN CAPITAL LETTER I WITH ACUTE */
 XKIcircumflex              =     0x00ce  /* U+00CE LATIN CAPITAL LETTER I WITH CIRCUMFLEX */
 XKIdiaeresis               =     0x00cf  /* U+00CF LATIN CAPITAL LETTER I WITH DIAERESIS */
 XKETH                      =     0x00d0  /* U+00D0 LATIN CAPITAL LETTER ETH */
 XKEth                      =     0x00d0  /* deprecated */
 XKNtilde                   =     0x00d1  /* U+00D1 LATIN CAPITAL LETTER N WITH TILDE */
 XKOgrave                   =     0x00d2  /* U+00D2 LATIN CAPITAL LETTER O WITH GRAVE */
 XKOacute                   =     0x00d3  /* U+00D3 LATIN CAPITAL LETTER O WITH ACUTE */
 XKOcircumflex              =     0x00d4  /* U+00D4 LATIN CAPITAL LETTER O WITH CIRCUMFLEX */
 XKOtilde                   =     0x00d5  /* U+00D5 LATIN CAPITAL LETTER O WITH TILDE */
 XKOdiaeresis               =     0x00d6  /* U+00D6 LATIN CAPITAL LETTER O WITH DIAERESIS */
 XKmultiply                 =     0x00d7  /* U+00D7 MULTIPLICATION SIGN */
 XKOslash                   =     0x00d8  /* U+00D8 LATIN CAPITAL LETTER O WITH STROKE */
 XKOoblique                 =     0x00d8  /* U+00D8 LATIN CAPITAL LETTER O WITH STROKE */
 XKUgrave                   =     0x00d9  /* U+00D9 LATIN CAPITAL LETTER U WITH GRAVE */
 XKUacute                   =     0x00da  /* U+00DA LATIN CAPITAL LETTER U WITH ACUTE */
 XKUcircumflex              =     0x00db  /* U+00DB LATIN CAPITAL LETTER U WITH CIRCUMFLEX */
 XKUdiaeresis               =     0x00dc  /* U+00DC LATIN CAPITAL LETTER U WITH DIAERESIS */
 XKYacute                   =     0x00dd  /* U+00DD LATIN CAPITAL LETTER Y WITH ACUTE */
 XKTHORN                    =     0x00de  /* U+00DE LATIN CAPITAL LETTER THORN */
 XKThorn                    =     0x00de  /* deprecated */
 XKssharp                   =     0x00df  /* U+00DF LATIN SMALL LETTER SHARP S */
 XKagrave                   =     0x00e0  /* U+00E0 LATIN SMALL LETTER A WITH GRAVE */
 XKaacute                   =     0x00e1  /* U+00E1 LATIN SMALL LETTER A WITH ACUTE */
 XKacircumflex              =     0x00e2  /* U+00E2 LATIN SMALL LETTER A WITH CIRCUMFLEX */
 XKatilde                   =     0x00e3  /* U+00E3 LATIN SMALL LETTER A WITH TILDE */
 XKadiaeresis               =     0x00e4  /* U+00E4 LATIN SMALL LETTER A WITH DIAERESIS */
 XKaring                    =     0x00e5  /* U+00E5 LATIN SMALL LETTER A WITH RING ABOVE */
 XKae                       =     0x00e6  /* U+00E6 LATIN SMALL LETTER AE */
 XKccedilla                 =     0x00e7  /* U+00E7 LATIN SMALL LETTER C WITH CEDILLA */
 XKegrave                   =     0x00e8  /* U+00E8 LATIN SMALL LETTER E WITH GRAVE */
 XKeacute                   =     0x00e9  /* U+00E9 LATIN SMALL LETTER E WITH ACUTE */
 XKecircumflex              =     0x00ea  /* U+00EA LATIN SMALL LETTER E WITH CIRCUMFLEX */
 XKediaeresis               =     0x00eb  /* U+00EB LATIN SMALL LETTER E WITH DIAERESIS */
 XKigrave                   =     0x00ec  /* U+00EC LATIN SMALL LETTER I WITH GRAVE */
 XKiacute                   =     0x00ed  /* U+00ED LATIN SMALL LETTER I WITH ACUTE */
 XKicircumflex              =     0x00ee  /* U+00EE LATIN SMALL LETTER I WITH CIRCUMFLEX */
 XKidiaeresis               =     0x00ef  /* U+00EF LATIN SMALL LETTER I WITH DIAERESIS */
 XKeth                      =     0x00f0  /* U+00F0 LATIN SMALL LETTER ETH */
 XKntilde                   =     0x00f1  /* U+00F1 LATIN SMALL LETTER N WITH TILDE */
 XKograve                   =     0x00f2  /* U+00F2 LATIN SMALL LETTER O WITH GRAVE */
 XKoacute                   =     0x00f3  /* U+00F3 LATIN SMALL LETTER O WITH ACUTE */
 XKocircumflex              =     0x00f4  /* U+00F4 LATIN SMALL LETTER O WITH CIRCUMFLEX */
 XKotilde                   =     0x00f5  /* U+00F5 LATIN SMALL LETTER O WITH TILDE */
 XKodiaeresis               =     0x00f6  /* U+00F6 LATIN SMALL LETTER O WITH DIAERESIS */
 XKdivision                 =     0x00f7  /* U+00F7 DIVISION SIGN */
 XKoslash                   =     0x00f8  /* U+00F8 LATIN SMALL LETTER O WITH STROKE */
 XKooblique                 =     0x00f8  /* U+00F8 LATIN SMALL LETTER O WITH STROKE */
 XKugrave                   =     0x00f9  /* U+00F9 LATIN SMALL LETTER U WITH GRAVE */
 XKuacute                   =     0x00fa  /* U+00FA LATIN SMALL LETTER U WITH ACUTE */
 XKucircumflex              =     0x00fb  /* U+00FB LATIN SMALL LETTER U WITH CIRCUMFLEX */
 XKudiaeresis               =     0x00fc  /* U+00FC LATIN SMALL LETTER U WITH DIAERESIS */
 XKyacute                   =     0x00fd  /* U+00FD LATIN SMALL LETTER Y WITH ACUTE */
 XKthorn                    =     0x00fe  /* U+00FE LATIN SMALL LETTER THORN */
 XKydiaeresis               =     0x00ff  /* U+00FF LATIN SMALL LETTER Y WITH DIAERESIS */
/* * Latin 2 * Byte 3 = 1 */
 XKAogonek                  =     0x01a1  /* U+0104 LATIN CAPITAL LETTER A WITH OGONEK */
 XKbreve                    =     0x01a2  /* U+02D8 BREVE */
 XKLstroke                  =     0x01a3  /* U+0141 LATIN CAPITAL LETTER L WITH STROKE */
 XKLcaron                   =     0x01a5  /* U+013D LATIN CAPITAL LETTER L WITH CARON */
 XKSacute                   =     0x01a6  /* U+015A LATIN CAPITAL LETTER S WITH ACUTE */
 XKScaron                   =     0x01a9  /* U+0160 LATIN CAPITAL LETTER S WITH CARON */
 XKScedilla                 =     0x01aa  /* U+015E LATIN CAPITAL LETTER S WITH CEDILLA */
 XKTcaron                   =     0x01ab  /* U+0164 LATIN CAPITAL LETTER T WITH CARON */
 XKZacute                   =     0x01ac  /* U+0179 LATIN CAPITAL LETTER Z WITH ACUTE */
 XKZcaron                   =     0x01ae  /* U+017D LATIN CAPITAL LETTER Z WITH CARON */
 XKZabovedot                =     0x01af  /* U+017B LATIN CAPITAL LETTER Z WITH DOT ABOVE */
 XKaogonek                  =     0x01b1  /* U+0105 LATIN SMALL LETTER A WITH OGONEK */
 XKogonek                   =     0x01b2  /* U+02DB OGONEK */
 XKlstroke                  =     0x01b3  /* U+0142 LATIN SMALL LETTER L WITH STROKE */
 XKlcaron                   =     0x01b5  /* U+013E LATIN SMALL LETTER L WITH CARON */
 XKsacute                   =     0x01b6  /* U+015B LATIN SMALL LETTER S WITH ACUTE */
 XKcaron                    =     0x01b7  /* U+02C7 CARON */
 XKscaron                   =     0x01b9  /* U+0161 LATIN SMALL LETTER S WITH CARON */
 XKscedilla                 =     0x01ba  /* U+015F LATIN SMALL LETTER S WITH CEDILLA */
 XKtcaron                   =     0x01bb  /* U+0165 LATIN SMALL LETTER T WITH CARON */
 XKzacute                   =     0x01bc  /* U+017A LATIN SMALL LETTER Z WITH ACUTE */
 XKdoubleacute              =     0x01bd  /* U+02DD DOUBLE ACUTE ACCENT */
 XKzcaron                   =     0x01be  /* U+017E LATIN SMALL LETTER Z WITH CARON */
 XKzabovedot                =     0x01bf  /* U+017C LATIN SMALL LETTER Z WITH DOT ABOVE */
 XKRacute                   =     0x01c0  /* U+0154 LATIN CAPITAL LETTER R WITH ACUTE */
 XKAbreve                   =     0x01c3  /* U+0102 LATIN CAPITAL LETTER A WITH BREVE */
 XKLacute                   =     0x01c5  /* U+0139 LATIN CAPITAL LETTER L WITH ACUTE */
 XKCacute                   =     0x01c6  /* U+0106 LATIN CAPITAL LETTER C WITH ACUTE */
 XKCcaron                   =     0x01c8  /* U+010C LATIN CAPITAL LETTER C WITH CARON */
 XKEogonek                  =     0x01ca  /* U+0118 LATIN CAPITAL LETTER E WITH OGONEK */
 XKEcaron                   =     0x01cc  /* U+011A LATIN CAPITAL LETTER E WITH CARON */
 XKDcaron                   =     0x01cf  /* U+010E LATIN CAPITAL LETTER D WITH CARON */
 XKDstroke                  =     0x01d0  /* U+0110 LATIN CAPITAL LETTER D WITH STROKE */
 XKNacute                   =     0x01d1  /* U+0143 LATIN CAPITAL LETTER N WITH ACUTE */
 XKNcaron                   =     0x01d2  /* U+0147 LATIN CAPITAL LETTER N WITH CARON */
 XKOdoubleacute             =     0x01d5  /* U+0150 LATIN CAPITAL LETTER O WITH DOUBLE ACUTE */
 XKRcaron                   =     0x01d8  /* U+0158 LATIN CAPITAL LETTER R WITH CARON */
 XKUring                    =     0x01d9  /* U+016E LATIN CAPITAL LETTER U WITH RING ABOVE */
 XKUdoubleacute             =     0x01db  /* U+0170 LATIN CAPITAL LETTER U WITH DOUBLE ACUTE */
 XKTcedilla                 =     0x01de  /* U+0162 LATIN CAPITAL LETTER T WITH CEDILLA */
 XKracute                   =     0x01e0  /* U+0155 LATIN SMALL LETTER R WITH ACUTE */
 XKabreve                   =     0x01e3  /* U+0103 LATIN SMALL LETTER A WITH BREVE */
 XKlacute                   =     0x01e5  /* U+013A LATIN SMALL LETTER L WITH ACUTE */
 XKcacute                   =     0x01e6  /* U+0107 LATIN SMALL LETTER C WITH ACUTE */
 XKccaron                   =     0x01e8  /* U+010D LATIN SMALL LETTER C WITH CARON */
 XKeogonek                  =     0x01ea  /* U+0119 LATIN SMALL LETTER E WITH OGONEK */
 XKecaron                   =     0x01ec  /* U+011B LATIN SMALL LETTER E WITH CARON */
 XKdcaron                   =     0x01ef  /* U+010F LATIN SMALL LETTER D WITH CARON */
 XKdstroke                  =     0x01f0  /* U+0111 LATIN SMALL LETTER D WITH STROKE */
 XKnacute                   =     0x01f1  /* U+0144 LATIN SMALL LETTER N WITH ACUTE */
 XKncaron                   =     0x01f2  /* U+0148 LATIN SMALL LETTER N WITH CARON */
 XKodoubleacute             =     0x01f5  /* U+0151 LATIN SMALL LETTER O WITH DOUBLE ACUTE */
 XKudoubleacute             =     0x01fb  /* U+0171 LATIN SMALL LETTER U WITH DOUBLE ACUTE */
 XKrcaron                   =     0x01f8  /* U+0159 LATIN SMALL LETTER R WITH CARON */
 XKuring                    =     0x01f9  /* U+016F LATIN SMALL LETTER U WITH RING ABOVE */
 XKtcedilla                 =     0x01fe  /* U+0163 LATIN SMALL LETTER T WITH CEDILLA */
 XKabovedot                 =     0x01ff  /* U+02D9 DOT ABOVE */
/* * Latin 3 * Byte 3 = 2 */
 XKHstroke                  =     0x02a1  /* U+0126 LATIN CAPITAL LETTER H WITH STROKE */
 XKHcircumflex              =     0x02a6  /* U+0124 LATIN CAPITAL LETTER H WITH CIRCUMFLEX */
 XKIabovedot                =     0x02a9  /* U+0130 LATIN CAPITAL LETTER I WITH DOT ABOVE */
 XKGbreve                   =     0x02ab  /* U+011E LATIN CAPITAL LETTER G WITH BREVE */
 XKJcircumflex              =     0x02ac  /* U+0134 LATIN CAPITAL LETTER J WITH CIRCUMFLEX */
 XKhstroke                  =     0x02b1  /* U+0127 LATIN SMALL LETTER H WITH STROKE */
 XKhcircumflex              =     0x02b6  /* U+0125 LATIN SMALL LETTER H WITH CIRCUMFLEX */
 XKidotless                 =     0x02b9  /* U+0131 LATIN SMALL LETTER DOTLESS I */
 XKgbreve                   =     0x02bb  /* U+011F LATIN SMALL LETTER G WITH BREVE */
 XKjcircumflex              =     0x02bc  /* U+0135 LATIN SMALL LETTER J WITH CIRCUMFLEX */
 XKCabovedot                =     0x02c5  /* U+010A LATIN CAPITAL LETTER C WITH DOT ABOVE */
 XKCcircumflex              =     0x02c6  /* U+0108 LATIN CAPITAL LETTER C WITH CIRCUMFLEX */
 XKGabovedot                =     0x02d5  /* U+0120 LATIN CAPITAL LETTER G WITH DOT ABOVE */
 XKGcircumflex              =     0x02d8  /* U+011C LATIN CAPITAL LETTER G WITH CIRCUMFLEX */
 XKUbreve                   =     0x02dd  /* U+016C LATIN CAPITAL LETTER U WITH BREVE */
 XKScircumflex              =     0x02de  /* U+015C LATIN CAPITAL LETTER S WITH CIRCUMFLEX */
 XKcabovedot                =     0x02e5  /* U+010B LATIN SMALL LETTER C WITH DOT ABOVE */
 XKccircumflex              =     0x02e6  /* U+0109 LATIN SMALL LETTER C WITH CIRCUMFLEX */
 XKgabovedot                =     0x02f5  /* U+0121 LATIN SMALL LETTER G WITH DOT ABOVE */
 XKgcircumflex              =     0x02f8  /* U+011D LATIN SMALL LETTER G WITH CIRCUMFLEX */
 XKubreve                   =     0x02fd  /* U+016D LATIN SMALL LETTER U WITH BREVE */
 XKscircumflex              =     0x02fe  /* U+015D LATIN SMALL LETTER S WITH CIRCUMFLEX */
/* * Latin 4 * Byte 3 = 3 */
 XKkra                      =     0x03a2  /* U+0138 LATIN SMALL LETTER KRA */
 XKkappa                    =     0x03a2  /* deprecated */
 XKRcedilla                 =     0x03a3  /* U+0156 LATIN CAPITAL LETTER R WITH CEDILLA */
 XKItilde                   =     0x03a5  /* U+0128 LATIN CAPITAL LETTER I WITH TILDE */
 XKLcedilla                 =     0x03a6  /* U+013B LATIN CAPITAL LETTER L WITH CEDILLA */
 XKEmacron                  =     0x03aa  /* U+0112 LATIN CAPITAL LETTER E WITH MACRON */
 XKGcedilla                 =     0x03ab  /* U+0122 LATIN CAPITAL LETTER G WITH CEDILLA */
 XKTslash                   =     0x03ac  /* U+0166 LATIN CAPITAL LETTER T WITH STROKE */
 XKrcedilla                 =     0x03b3  /* U+0157 LATIN SMALL LETTER R WITH CEDILLA */
 XKitilde                   =     0x03b5  /* U+0129 LATIN SMALL LETTER I WITH TILDE */
 XKlcedilla                 =     0x03b6  /* U+013C LATIN SMALL LETTER L WITH CEDILLA */
 XKemacron                  =     0x03ba  /* U+0113 LATIN SMALL LETTER E WITH MACRON */
 XKgcedilla                 =     0x03bb  /* U+0123 LATIN SMALL LETTER G WITH CEDILLA */
 XKtslash                   =     0x03bc  /* U+0167 LATIN SMALL LETTER T WITH STROKE */
 XKENG                      =     0x03bd  /* U+014A LATIN CAPITAL LETTER ENG */
 XKeng                      =     0x03bf  /* U+014B LATIN SMALL LETTER ENG */
 XKAmacron                  =     0x03c0  /* U+0100 LATIN CAPITAL LETTER A WITH MACRON */
 XKIogonek                  =     0x03c7  /* U+012E LATIN CAPITAL LETTER I WITH OGONEK */
 XKEabovedot                =     0x03cc  /* U+0116 LATIN CAPITAL LETTER E WITH DOT ABOVE */
 XKImacron                  =     0x03cf  /* U+012A LATIN CAPITAL LETTER I WITH MACRON */
 XKNcedilla                 =     0x03d1  /* U+0145 LATIN CAPITAL LETTER N WITH CEDILLA */
 XKOmacron                  =     0x03d2  /* U+014C LATIN CAPITAL LETTER O WITH MACRON */
 XKKcedilla                 =     0x03d3  /* U+0136 LATIN CAPITAL LETTER K WITH CEDILLA */
 XKUogonek                  =     0x03d9  /* U+0172 LATIN CAPITAL LETTER U WITH OGONEK */
 XKUtilde                   =     0x03dd  /* U+0168 LATIN CAPITAL LETTER U WITH TILDE */
 XKUmacron                  =     0x03de  /* U+016A LATIN CAPITAL LETTER U WITH MACRON */
 XKamacron                  =     0x03e0  /* U+0101 LATIN SMALL LETTER A WITH MACRON */
 XKiogonek                  =     0x03e7  /* U+012F LATIN SMALL LETTER I WITH OGONEK */
 XKeabovedot                =     0x03ec  /* U+0117 LATIN SMALL LETTER E WITH DOT ABOVE */
 XKimacron                  =     0x03ef  /* U+012B LATIN SMALL LETTER I WITH MACRON */
 XKncedilla                 =     0x03f1  /* U+0146 LATIN SMALL LETTER N WITH CEDILLA */
 XKomacron                  =     0x03f2  /* U+014D LATIN SMALL LETTER O WITH MACRON */
 XKkcedilla                 =     0x03f3  /* U+0137 LATIN SMALL LETTER K WITH CEDILLA */
 XKuogonek                  =     0x03f9  /* U+0173 LATIN SMALL LETTER U WITH OGONEK */
 XKutilde                   =     0x03fd  /* U+0169 LATIN SMALL LETTER U WITH TILDE */
 XKumacron                  =     0x03fe  /* U+016B LATIN SMALL LETTER U WITH MACRON */
/* * Latin 8 */
 XKBabovedot                =  0x1001e02  /* U+1E02 LATIN CAPITAL LETTER B WITH DOT ABOVE */
 XKbabovedot                =  0x1001e03  /* U+1E03 LATIN SMALL LETTER B WITH DOT ABOVE */
 XKDabovedot                =  0x1001e0a  /* U+1E0A LATIN CAPITAL LETTER D WITH DOT ABOVE */
 XKWgrave                   =  0x1001e80  /* U+1E80 LATIN CAPITAL LETTER W WITH GRAVE */
 XKWacute                   =  0x1001e82  /* U+1E82 LATIN CAPITAL LETTER W WITH ACUTE */
 XKdabovedot                =  0x1001e0b  /* U+1E0B LATIN SMALL LETTER D WITH DOT ABOVE */
 XKYgrave                   =  0x1001ef2  /* U+1EF2 LATIN CAPITAL LETTER Y WITH GRAVE */
 XKFabovedot                =  0x1001e1e  /* U+1E1E LATIN CAPITAL LETTER F WITH DOT ABOVE */
 XKfabovedot                =  0x1001e1f  /* U+1E1F LATIN SMALL LETTER F WITH DOT ABOVE */
 XKMabovedot                =  0x1001e40  /* U+1E40 LATIN CAPITAL LETTER M WITH DOT ABOVE */
 XKmabovedot                =  0x1001e41  /* U+1E41 LATIN SMALL LETTER M WITH DOT ABOVE */
 XKPabovedot                =  0x1001e56  /* U+1E56 LATIN CAPITAL LETTER P WITH DOT ABOVE */
 XKwgrave                   =  0x1001e81  /* U+1E81 LATIN SMALL LETTER W WITH GRAVE */
 XKpabovedot                =  0x1001e57  /* U+1E57 LATIN SMALL LETTER P WITH DOT ABOVE */
 XKwacute                   =  0x1001e83  /* U+1E83 LATIN SMALL LETTER W WITH ACUTE */
 XKSabovedot                =  0x1001e60  /* U+1E60 LATIN CAPITAL LETTER S WITH DOT ABOVE */
 XKygrave                   =  0x1001ef3  /* U+1EF3 LATIN SMALL LETTER Y WITH GRAVE */
 XKWdiaeresis               =  0x1001e84  /* U+1E84 LATIN CAPITAL LETTER W WITH DIAERESIS */
 XKwdiaeresis               =  0x1001e85  /* U+1E85 LATIN SMALL LETTER W WITH DIAERESIS */
 XKsabovedot                =  0x1001e61  /* U+1E61 LATIN SMALL LETTER S WITH DOT ABOVE */
 XKWcircumflex              =  0x1000174  /* U+0174 LATIN CAPITAL LETTER W WITH CIRCUMFLEX */
 XKTabovedot                =  0x1001e6a  /* U+1E6A LATIN CAPITAL LETTER T WITH DOT ABOVE */
 XKYcircumflex              =  0x1000176  /* U+0176 LATIN CAPITAL LETTER Y WITH CIRCUMFLEX */
 XKwcircumflex              =  0x1000175  /* U+0175 LATIN SMALL LETTER W WITH CIRCUMFLEX */
 XKtabovedot                =  0x1001e6b  /* U+1E6B LATIN SMALL LETTER T WITH DOT ABOVE */
 XKycircumflex              =  0x1000177  /* U+0177 LATIN SMALL LETTER Y WITH CIRCUMFLEX */
/* * Latin 9 * Byte 3 = 0x13 */
 XKOE                       =     0x13bc  /* U+0152 LATIN CAPITAL LIGATURE OE */
 XKoe                       =     0x13bd  /* U+0153 LATIN SMALL LIGATURE OE */
 XKYdiaeresis               =     0x13be  /* U+0178 LATIN CAPITAL LETTER Y WITH DIAERESIS */


 XKEcuSign                  =  0x10020a0  /* U+20A0 EURO-CURRENCY SIGN */
 XKColonSign                =  0x10020a1  /* U+20A1 COLON SIGN */
 XKCruzeiroSign             =  0x10020a2  /* U+20A2 CRUZEIRO SIGN */
 XKFFrancSign               =  0x10020a3  /* U+20A3 FRENCH FRANC SIGN */
 XKLiraSign                 =  0x10020a4  /* U+20A4 LIRA SIGN */
 XKMillSign                 =  0x10020a5  /* U+20A5 MILL SIGN */
 XKNairaSign                =  0x10020a6  /* U+20A6 NAIRA SIGN */
 XKPesetaSign               =  0x10020a7  /* U+20A7 PESETA SIGN */
 XKRupeeSign                =  0x10020a8  /* U+20A8 RUPEE SIGN */
 XKWonSign                  =  0x10020a9  /* U+20A9 WON SIGN */
 XKNewSheqelSign            =  0x10020aa  /* U+20AA NEW SHEQEL SIGN */
 XKDongSign                 =  0x10020ab  /* U+20AB DONG SIGN */
 XKEuroSign                 =     0x20ac  /* U+20AC EURO SIGN */
)
